import os
from dotenv import load_dotenv

load_dotenv()

# Movidesk
movidesk_url_api_publica = 'https://api.movidesk.com/public/v1'
movidesk_url_api_interna_old = "https://movidesk-api.internal/public/v1/",
movidesk_url_api_interna = 'https://localhost:4443/public/v1'
movidesk_endpoint_tickets = '/tickets'
movidesk_endpoint_persons = '/persons'
movidesk_endpoint_ticket_file = '/ticketFileUpload'
movidesk_base_url_attachments = 'https://s3.amazonaws.com/movidesk-files/'
domain_movidesk = ''
url_movidesk = f'{domain_movidesk} + movidesk.com'

# .env
database = str(os.getenv('database'))
movidesk_url_api = str(os.getenv('movidesk_url_api'))
token_movidesk_origin = str(os.getenv('token_movidesk_origin'))  # Base Felipe
token_movidesk_destin = str(os.getenv('token_movidesk_destin'))  # Base Jhow
tenant_id_origin = int(os.getenv('tenant_id_origin'))
tenant_id_destin = int(os.getenv('tenant_id_destin'))
person_type = int(os.getenv('person_type'))  # Tipo da pessoa. Pessoa = 1, Empresa = 2, Departamento = 4.
profile_type = int(os.getenv('profile_type'))  # Tipo do perfil. Agente = 1, Cliente = 2, Agente e Cliente = 3.
top = int(os.getenv('top'))
skip = int(os.getenv('skip'))
page = int(os.getenv('page'))
step = int(os.getenv('step'))  # 1= Migrar pessoas; 2= Migrar tickets ; 5= Remigrar pessoas; 6= Remigrar tickets

api_movidesk = {
    'publica': 'https://api.movidesk.com/public/v1',
    # 'interna': 'https://movidesk-api.internal/public/v1'
    'interna': 'https://localhost:4443/public/v1/'

}

endpoint_movidesk = {
    "tickets": '/tickets',
    "persons": '/persons',
    "ticket_file": '/ticketFileUpload'
}

dict_ext_mime = {
    ".3dm": ["x-world/x-3dmf"],
    ".3dmf": ["x-world/x-3dmf"],
    ".3g2": ["video/3gpp2", "audio/3gpp2"],
    ".3gp": ["video/3gpp", "audio/3gpp"],
    ".7z": ["application/x-7z-compressed"],
    ".a": ["application/octet-stream"],
    ".aab": ["application/x-authorware-bin"],
    ".aac": ["audio/aac"],
    ".aam": ["application/x-authorware-map"],
    ".aas": ["application/x-authorware-seg"],
    ".abc": ["text/vnd.abc"],
    ".abw": ["application/x-abiword"],
    ".acgi": ["text/html"],
    ".afl": ["video/animaflex"],
    ".ai": ["application/postscript"],
    ".aif": ["audio/aiff", "audio/x-aiff"],
    ".aifc": ["audio/aiff", "audio/x-aiff"],
    ".aiff": ["audio/aiff", "audio/x-aiff"],
    ".aim": ["application/x-aim"],
    ".aip": ["text/x-audiosoft-intra"],
    ".ani": ["application/x-navi-animation"],
    ".aos": ["application/x-nokia-9000-communicator-add-on-software"],
    ".apk": ["application/vnd.android.package-archive"],
    ".aps": ["application/mime"],
    ".arc": ["application/octet-stream"],
    ".arj": ["application/arj", "application/octet-stream"],
    ".art": ["image/x-jg"],
    ".asf": ["video/x-ms-asf"],
    ".asm": ["text/x-asm"],
    ".asp": ["text/asp"],
    ".asx": ["application/x-mplayer2", "video/x-ms-asf", "video/x-ms-asf-plugin"],
    ".au": ["audio/basic", "audio/x-au"],
    ".avi": ["application/x-troff-msvideo", "video/avi", "video/msvideo", "video/x-msvideo"],
    ".avs": ["video/avs-video"],
    ".azw": ["application/vnd.amazon.ebook"],
    ".bcpio": ["application/x-bcpio"],
    ".bin": ["application/mac-binary", "application/macbinary", "application/octet-stream", "application/x-binary",
             "application/x-macbinary"],
    ".bm": ["image/bmp"],
    ".bmp": ["image/bmp", "image/x-windows-bmp"],
    ".boo": ["application/book"],
    ".book": ["application/book"],
    ".boz": ["application/x-bzip2"],
    ".bsh": ["application/x-bsh"],
    ".bz": ["application/x-bzip"],
    ".bz2": ["application/x-bzip2"],
    ".c": ["text/plain", "text/x-c"],
    ".c++": ["text/plain"],
    ".cat": ["application/vnd.ms-pki.seccat"],
    ".cc": ["text/plain", "text/x-c"],
    ".ccad": ["application/clariscad"],
    ".cco": ["application/x-cocoa"],
    ".cdf": ["application/cdf", "application/x-cdf", "application/x-netcdf"],
    ".cer": ["application/pkix-cert", "application/x-x509-ca-cert"],
    ".cha": ["application/x-chat"],
    ".chat": ["application/x-chat"],
    ".class": ["application/java", "application/java-byte-code", "application/x-java-class"],
    ".com": ["application/octet-stream", "text/plain"],
    ".conf": ["text/plain"],
    ".cpio": ["application/x-cpio"],
    ".cpp": ["text/x-c"],
    ".cpt": ["application/mac-compactpro", "application/x-compactpro", "application/x-cpt"],
    ".crl": ["application/pkcs-crl", "application/pkix-crl", "application/pkix-cert", "application/x-x509-ca-cert",
             "application/x-x509-user-cert"],
    ".csh": ["application/x-csh", "text/x-script.csh"],
    ".css": ["text/css", "application/x-pointplus"],
    ".csv": ["text/csv"],
    ".cxx": ["text/plain"],
    ".dcr": ["application/x-director"],
    ".deepv": ["application/x-deepv"],
    ".def": ["text/plain"],
    ".der": ["application/x-x509-ca-cert"],
    ".dif": ["video/x-dv"],
    ".dir": ["application/x-director"],
    ".dl": ["video/dl", "video/x-dl"],
    ".doc": ["application/msword"],
    ".docx": ["application/msword"],
    ".dot": ["application/msword"],
    ".dp": ["application/commonground"],
    ".drw": ["application/drafting"],
    ".dump": ["application/octet-stream"],
    ".dv": ["video/x-dv"],
    ".dvi": ["application/x-dvi"],
    ".dwf": ["model/vnd.dwf", "drawing/x-dwf (old)"],
    ".dwg": ["application/acad", "image/vnd.dwg", "image/x-dwg"],
    ".dxf": ["application/dxf", "image/vnd.dwg", "image/x-dwg"],
    ".dxr": ["application/x-director"],
    ".el": ["text/x-script.elisp"],
    ".elc": ["application/x-elc", "application/x-bytecode.elisp (compiled elisp)"],
    ".appsettings": ["application/x-envoy"],
    ".eot": ["application/vnd.ms-fontobject"],
    ".eps": ["application/postscript"],
    ".epub": ["application/epub+zip"],
    ".es": ["application/x-esrehber"],
    ".etx": ["text/x-setext"],
    ".evy": ["application/envoy", "application/x-envoy"],
    ".exe": ["application/octet-stream"],
    ".f": ["text/plain", "text/x-fortran"],
    ".f77": ["text/x-fortran"],
    ".f90": ["text/plain", "text/x-fortran"],
    ".fdf": ["application/vnd.fdf"],
    ".fif": ["image/fif", "application/fractals"],
    ".fli": ["video/fli", "video/x-fli"],
    ".flo": ["image/florian"],
    ".flx": ["text/vnd.fmi.flexstor"],
    ".fmf": ["video/x-atomic3d-feature"],
    ".for": ["text/plain", "text/x-fortran"],
    ".fpx": ["image/vnd.net-fpx", "image/vnd.fpx"],
    ".frl": ["application/freeloader"],
    ".funk": ["audio/make"],
    ".g": ["text/plain"],
    ".g3": ["image/g3fax"],
    ".gif": ["image/gif"],
    ".gl": ["video/gl", "video/x-gl"],
    ".gsd": ["audio/x-gsm"],
    ".gsm": ["audio/x-gsm"],
    ".gsp": ["application/x-gsp"],
    ".gss": ["application/x-gss"],
    ".gtar": ["application/x-gtar"],
    ".gz": ["application/x-gzip", "application/x-compressed"],
    ".gzip": ["application/x-gzip", "multipart/x-gzip"],
    ".h": ["text/plain", "text/x-h"],
    ".hdf": ["application/x-hdf"],
    ".help": ["application/x-helpfile"],
    ".hgl": ["application/vnd.hp-hpgl"],
    ".hh": ["text/plain", "text/x-h"],
    ".hlb": ["text/x-script"],
    ".hlp": ["application/hlp", "application/x-helpfile", "application/x-winhelp"],
    ".hpg": ["application/vnd.hp-hpgl"],
    ".hpgl": ["application/vnd.hp-hpgl"],
    ".hqx": ["application/binhex", "application/binhex4", "application/mac-binhex", "application/mac-binhex40",
             "application/x-binhex40", "application/x-mac-binhex40"],
    ".hta": ["application/hta"],
    ".htc": ["text/x-component"],
    ".htm": ["text/html"],
    ".html": ["text/html"],
    ".htmls": ["text/html"],
    ".htt": ["text/webviewhtml"],
    ".htx": ["text/html"],
    ".ice": ["x-conference/x-cooltalk"],
    ".ico": ["image/x-icon"],
    ".ics": ["text/calendar"],
    ".idc": ["text/plain"],
    ".ief": ["image/ief"],
    ".iefs": ["image/ief"],
    ".iges": ["application/iges", "model/iges"],
    ".igs": ["application/iges", "model/iges"],
    ".ima": ["application/x-ima"],
    ".imap": ["application/x-httpd-imap"],
    ".inf": ["application/inf"],
    ".ins": ["application/x-internett-signup"],
    ".ip": ["application/x-ip2"],
    ".isu": ["video/x-isvideo"],
    ".it": ["audio/it"],
    ".iv": ["application/x-inventor"],
    ".ivr": ["i-world/i-vrml"],
    ".ivy": ["application/x-livescreen"],
    ".jam": ["audio/x-jam"],
    ".jar": ["application/java-archive"],
    ".jav": ["text/plain", "text/x-java-source"],
    ".java": ["text/plain", "text/x-java-source"],
    ".jcm": ["application/x-java-commerce"],
    ".jfif": ["image/jpeg", "image/pjpeg"],
    ".jfif-tbnl": ["image/jpeg"],
    ".jpe": ["image/jpeg", "image/pjpeg"],
    ".jpeg": ["image/jpeg", "image/pjpeg"],
    ".jpg": ["image/jpeg", "image/pjpeg"],
    ".jps": ["image/x-jps"],
    ".js": ["application/javascript", "application/ecmascript", "application/x-javascript", "text/ecmascript",
            "text/javascript"],
    ".json": ["application/json"],
    ".jut": ["image/jutvision"],
    ".kar": ["audio/midi", "music/x-karaoke"],
    ".ksh": ["application/x-ksh", "text/x-script.ksh"],
    ".la": ["audio/nspaudio", "audio/x-nspaudio"],
    ".lam": ["audio/x-liveaudio"],
    ".latex": ["application/x-latex"],
    ".lha": ["application/lha", "application/octet-stream", "application/x-lha"],
    ".lhx": ["application/octet-stream"],
    ".list": ["text/plain"],
    ".lma": ["audio/nspaudio", "audio/x-nspaudio"],
    ".log": ["text/plain"],
    ".lsp": ["application/x-lisp", "text/x-script.lisp"],
    ".lst": ["text/plain"],
    ".lsx": ["text/x-la-asf"],
    ".ltx": ["application/x-latex"],
    ".lzh": ["application/octet-stream", "application/x-lzh"],
    ".lzx": ["application/lzx", "application/octet-stream", "application/x-lzx"],
    ".m": ["text/plain", "text/x-m"],
    ".m1v": ["video/mpeg"],
    ".m2a": ["audio/mpeg"],
    ".m2v": ["video/mpeg"],
    ".m3u": ["audio/x-mpequrl"],
    ".m4a": ["audio/mp4a-latm"],
    ".m4v": ["video/x-m4v"],
    ".man": ["application/x-troff-man"],
    ".map": ["application/x-navimap"],
    ".mar": ["text/plain"],
    ".mbd": ["application/mbedlet"],
    ".mc$": ["application/x-magic-cap-package-1.0"],
    ".mcd": ["application/mcad", "application/x-mathcad"],
    ".mcf": ["image/vasa", "text/mcf"],
    ".mcp": ["application/netmc"],
    ".me": ["application/x-troff-me"],
    ".mht": ["message/rfc822"],
    ".mhtml": ["message/rfc822"],
    ".mid": ["audio/midi", "application/x-midi", "music/crescendo", "x-music/x-midi", "audio/x-mid"],
    ".midi": ["audio/midi", "application/x-midi", "audio/x-mid", "audio/x-midi", "music/crescendo", "x-music/x-midi"],
    ".mif": ["application/x-frame", "application/x-mif"],
    ".mime": ["message/rfc822", "www/mime"],
    ".mjf": ["audio/x-vnd.audioexplosion.mjuicemediafile"],
    ".mjpg": ["video/x-motion-jpeg"],
    ".mk3d": ["video/x-matroska-3d"],
    ".mka": ["audio/x-matroska"],
    ".mkv": ["video/x-matroska"],
    ".mm": ["application/base64", "application/x-meme"],
    ".mme": ["application/base64"],
    ".mod": ["audio/mod", "audio/x-mod"],
    ".moov": ["video/quicktime"],
    ".mov": ["video/quicktime"],
    ".movie": ["video/x-sgi-movie"],
    ".mp2": ["audio/mpeg", "video/x-mpeg", "video/x-mpeq2a"],
    ".mp3": ["audio/mpeg3", "audio/x-mpeg-3", "video/mpeg", "video/x-mpeg"],
    ".mpa": ["audio/mpeg"],
    ".mpc": ["application/x-project"],
    ".mpe": ["video/mpeg"],
    ".mpeg": ["video/mpeg"],
    ".mpg": ["audio/mpeg", "video/mpeg"],
    ".mpga": ["audio/mpeg"],
    ".mpkg": ["application/vnd.apple.installer+xml"],
    ".mpp": ["application/vnd.ms-project"],
    ".mpt": ["application/x-project"],
    ".mpv": ["application/x-project"],
    ".mpx": ["application/x-project"],
    ".mrc": ["application/marc"],
    ".ms": ["application/x-troff-ms"],
    ".mv": ["video/x-sgi-movie"],
    ".my": ["audio/make"],
    ".mzz": ["application/x-vnd.audioexplosion.mzz"],
    ".nap": ["image/naplps"],
    ".naplps": ["image/naplps"],
    ".nc": ["application/x-netcdf"],
    ".ncm": ["application/vnd.nokia.configuration-message"],
    ".nif": ["image/x-niff"],
    ".niff": ["image/x-niff"],
    ".nix": ["application/x-mix-transfer"],
    ".nsc": ["application/x-conference"],
    ".nvd": ["application/x-navidoc"],
    ".o": ["application/octet-stream"],
    ".oda": ["application/oda"],
    ".odp": ["application/vnd.oasis.opendocument.presentation"],
    ".ods": ["application/vnd.oasis.opendocument.spreadsheet"],
    ".odt": ["application/vnd.oasis.opendocument.text"],
    ".oga": ["audio/ogg"],
    ".ogv": ["video/ogg"],
    ".ogx": ["application/ogg"],
    ".omc": ["application/x-omc"],
    ".omcd": ["application/x-omcdatamaker"],
    ".omcr": ["application/x-omcregerator"],
    ".otf": ["font/otf"],
    ".p": ["text/x-pascal"],
    ".p10": ["application/pkcs10", "application/x-pkcs10"],
    ".p12": ["application/pkcs-12", "application/x-pkcs12"],
    ".p7a": ["application/x-pkcs7-signature"],
    ".p7c": ["application/pkcs7-mime", "application/x-pkcs7-mime"],
    ".p7m": ["application/pkcs7-mime", "application/x-pkcs7-mime"],
    ".p7r": ["application/x-pkcs7-certreqresp"],
    ".p7s": ["application/pkcs7-signature"],
    ".part": ["application/pro_eng"],
    ".pas": ["text/pascal"],
    ".pbm": ["image/x-portable-bitmap"],
    ".pcl": ["application/vnd.hp-pcl", "application/x-pcl"],
    ".pct": ["image/x-pict"],
    ".pcx": ["image/x-pcx"],
    ".pdb": ["chemical/x-pdb"],
    ".pdf": ["application/pdf"],
    ".pfunk": ["audio/make", "audio/make.my.funk"],
    ".pgm": ["image/x-portable-graymap"],
    ".pic": ["image/pict"],
    ".pict": ["image/pict"],
    ".pkg": ["application/x-newton-compatible-pkg"],
    ".pko": ["application/vnd.ms-pki.pko"],
    ".pl": ["text/plain", "text/x-script.perl"],
    ".plain": ["text/html"],
    ".plx": ["application/x-pixclscript"],
    ".pm": ["image/x-xpixmap", "text/x-script.perl-module"],
    ".pm4": ["application/x-pagemaker"],
    ".pm5": ["application/x-pagemaker"],
    ".png": ["image/png"],
    ".pnm": ["application/x-portable-anymap", "image/x-portable-anymap"],
    ".pot": ["application/mspowerpoint", "application/vnd.ms-powerpoint"],
    ".pov": ["model/x-pov"],
    ".ppa": ["application/vnd.ms-powerpoint"],
    ".ppm": ["image/x-portable-pixmap"],
    ".pps": ["application/mspowerpoint", "application/vnd.ms-powerpoint"],
    ".ppt": ["application/vnd.ms-powerpoint", "application/mspowerpoint", "application/powerpoint",
             "application/vnd.ms-powerpoint", "application/x-mspowerpoint"],
    ".ppz": ["application/mspowerpoint"],
    ".pre": ["application/x-freelance"],
    ".prt": ["application/pro_eng"],
    ".ps": ["application/postscript"],
    ".psd": ["application/octet-stream"],
    ".pvu": ["paleovu/x-pv"],
    ".pwz": ["application/vnd.ms-powerpoint"],
    ".py": ["text/x-script.phyton"],
    ".pyc": ["application/x-bytecode.python"],
    ".qcp": ["audio/vnd.qcelp"],
    ".qd3": ["x-world/x-3dmf"],
    ".qd3d": ["x-world/x-3dmf"],
    ".qif": ["image/x-quicktime"],
    ".qt": ["video/quicktime"],
    ".qtc": ["video/x-qtc"],
    ".qti": ["image/x-quicktime"],
    ".qtif": ["image/x-quicktime"],
    ".ra": ["audio/x-pn-realaudio", "audio/x-pn-realaudio-plugin", "audio/x-realaudio"],
    ".ram": ["audio/x-pn-realaudio"],
    ".rar": ["application/x-rar-compressed"],
    ".ras": ["application/x-cmu-raster", "image/cmu-raster", "image/x-cmu-raster"],
    ".rast": ["image/cmu-raster"],
    ".rexx": ["text/x-script.rexx"],
    ".rf": ["image/vnd.rn-realflash"],
    ".rgb": ["image/x-rgb"],
    ".rm": ["application/vnd.rn-realmedia", "audio/x-pn-realaudio"],
    ".rmi": ["audio/mid"],
    ".rmp": ["audio/x-pn-realaudio", "audio/x-pn-realaudio-plugin"],
    ".rng": ["application/ringing-tones", "application/vnd.nokia.ringing-tone"],
    ".rnx": ["application/vnd.rn-realplayer"],
    ".roff": ["application/x-troff"],
    ".rp": ["image/vnd.rn-realpix"],
    ".rpm": ["audio/x-pn-realaudio-plugin"],
    ".rt": ["text/richtext", "text/vnd.rn-realtext"],
    ".rtf": ["application/rtf", "text/richtext", "application/x-rtf"],
    ".rtx": ["text/richtext"],
    ".rv": ["video/vnd.rn-realvideo"],
    ".s": ["text/x-asm"],
    ".s3m": ["audio/s3m"],
    ".saveme": ["application/octet-stream"],
    ".sbk": ["application/x-tbook"],
    ".scm": ["application/x-lotusscreencam", "text/x-script.guile", "text/x-script.scheme", "video/x-scm"],
    ".sdml": ["text/plain"],
    ".sdp": ["application/sdp", "application/x-sdp"],
    ".sdr": ["application/sounder"],
    ".sea": ["application/sea", "application/x-sea"],
    ".set": ["application/set"],
    ".sgm": ["text/sgml", "text/x-sgml"],
    ".sgml": ["text/sgml", "text/x-sgml"],
    ".sh": ["application/x-sh", "application/x-bsh", "application/x-shar", "text/x-script.sh"],
    ".shar": ["application/x-bsh", "application/x-shar"],
    ".shtml": ["text/html", "text/x-server-parsed-html"],
    ".sid": ["audio/x-psid"],
    ".sit": ["application/x-sit", "application/x-stuffit"],
    ".skd": ["application/x-koan"],
    ".skm": ["application/x-koan"],
    ".skp": ["application/x-koan"],
    ".skt": ["application/x-koan"],
    ".sl": ["application/x-seelogo"],
    ".smi": ["application/smil"],
    ".smil": ["application/smil"],
    ".snd": ["audio/basic", "audio/x-adpcm"],
    ".sol": ["application/solids"],
    ".spc": ["text/x-speech", "application/x-pkcs7-certificates"],
    ".spl": ["application/futuresplash"],
    ".spr": ["application/x-sprite"],
    ".sprite": ["application/x-sprite"],
    ".src": ["application/x-wais-source"],
    ".ssi": ["text/x-server-parsed-html"],
    ".ssm": ["application/streamingmedia"],
    ".sst": ["application/vnd.ms-pki.certstore"],
    ".step": ["application/step"],
    ".stl": ["application/sla", "application/vnd.ms-pki.stl", "application/x-navistyle"],
    ".stp": ["application/step"],
    ".sv4cpio": ["application/x-sv4cpio"],
    ".sv4crc": ["application/x-sv4crc"],
    ".svf": ["image/vnd.dwg", "image/x-dwg"],
    ".svg": ["image/svg+xml"],
    ".svr": ["application/x-world", "x-world/x-svr"],
    ".swf": ["application/x-shockwave-flash"],
    ".t": ["application/x-troff"],
    ".talk": ["text/x-speech"],
    ".tar": ["application/x-tar"],
    ".tbk": ["application/toolbook", "application/x-tbook"],
    ".tcl": ["application/x-tcl", "text/x-script.tcl"],
    ".tcsh": ["text/x-script.tcsh"],
    ".tex": ["application/x-tex"],
    ".texi": ["application/x-texinfo"],
    ".texinfo": ["application/x-texinfo"],
    ".text": ["text/plain", "application/plain"],
    ".tgz": ["application/gnutar", "application/x-compressed"],
    ".tif": ["image/tiff", "image/x-tiff"],
    ".tiff": ["image/tiff", "image/x-tiff"],
    ".tr": ["application/x-troff"],
    ".ts": ["application/typescript"],
    ".tsi": ["audio/tsp-audio"],
    ".tsp": ["application/dsptype", "audio/tsplayer"],
    ".tsv": ["text/tab-separated-values"],
    ".ttf": ["font/ttf"],
    ".turbot": ["image/florian"],
    ".txt": ["text/plain"],
    ".uil": ["text/x-uil"],
    ".uni": ["text/uri-list"],
    ".unis": ["text/uri-list"],
    ".unv": ["application/i-deas"],
    ".uri": ["text/uri-list"],
    ".uris": ["text/uri-list"],
    ".ustar": ["application/x-ustar", "multipart/x-ustar"],
    ".uu": ["text/x-uuencode", "application/octet-stream"],
    ".uue": ["text/x-uuencode"],
    ".vcard": ["text/vcard"],
    ".vcd": ["application/x-cdlink"],
    ".vcf": ["text/vcard"],
    ".vcs": ["text/x-vcalendar"],
    ".vda": ["application/vda"],
    ".vdo": ["video/vdo"],
    ".vew": ["application/groupwise"],
    ".viv": ["video/vivo", "video/vnd.vivo"],
    ".vivo": ["video/vivo", "video/vnd.vivo"],
    ".vmd": ["application/vocaltec-media-desc"],
    ".vmf": ["application/vocaltec-media-file"],
    ".voc": ["audio/voc", "audio/x-voc"],
    ".vos": ["video/vosaic"],
    ".vox": ["audio/voxware"],
    ".vqe": ["audio/x-twinvq-plugin"],
    ".vqf": ["audio/x-twinvq"],
    ".vql": ["audio/x-twinvq-plugin"],
    ".vrml": ["application/x-vrml", "model/vrml", "x-world/x-vrml"],
    ".vrt": ["x-world/x-vrt"],
    ".vsd": ["application/vnd.visio", "application/x-visio"],
    ".vst": ["application/x-visio"],
    ".vsw": ["application/x-visio"],
    ".w60": ["application/wordperfect6.0"],
    ".w61": ["application/wordperfect6.1"],
    ".w6w": ["application/msword"],
    ".wav": ["audio/x-wav", "audio/wav"],
    ".wb1": ["application/x-qpro"],
    ".wbmp": ["image/vnd.wap.wbmp"],
    ".web": ["application/vnd.xara"],
    ".weba": ["audio/webm"],
    ".webm": ["video/webm"],
    ".webp": ["image/webp"],
    ".wiz": ["application/msword"],
    ".wk1": ["application/x-123"],
    ".wmf": ["windows/metafile"],
    ".wml": ["text/vnd.wap.wml"],
    ".wmlc": ["application/vnd.wap.wmlc"],
    ".wmls": ["text/vnd.wap.wmlscript"],
    ".wmlsc": ["application/vnd.wap.wmlscriptc"],
    ".woff": ["font/woff", "application/font-woff"],
    ".woff2": ["font/woff2", "application/font-woff"],
    ".word": ["application/msword"],
    ".wp": ["application/wordperfect"],
    ".wp5": ["application/wordperfect", "application/wordperfect6.0"],
    ".wp6": ["application/wordperfect"],
    ".wpd": ["application/wordperfect", "application/x-wpwin"],
    ".wq1": ["application/x-lotus"],
    ".wri": ["application/mswrite", "application/x-wri"],
    ".wrl": ["application/x-world", "model/vrml", "x-world/x-vrml"],
    ".wrz": ["model/vrml", "x-world/x-vrml"],
    ".wsc": ["text/scriplet"],
    ".wsrc": ["application/x-wais-source"],
    ".wtk": ["application/x-wintalk"],
    ".xbm": ["image/xbm", "image/x-xbitmap", "image/x-xbm"],
    ".xdr": ["video/x-amt-demorun"],
    ".xgz": ["xgl/drawing"],
    ".xhtml": ["application/xhtml+xml"],
    ".xif": ["image/vnd.xiff"],
    ".xl": ["application/excel"],
    ".xla": ["application/excel", "application/x-excel", "application/x-msexcel"],
    ".xlb": ["application/excel", "application/vnd.ms-excel", "application/x-excel"],
    ".xlc": ["application/excel", "application/vnd.ms-excel", "application/x-excel"],
    ".xld": ["application/excel", "application/x-excel"],
    ".xlk": ["application/excel", "application/x-excel"],
    ".xll": ["application/excel", "application/vnd.ms-excel", "application/x-excel"],
    ".xlm": ["application/excel", "application/vnd.ms-excel", "application/x-excel"],
    ".xls": ["application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
             "application/excel", "application/x-excel", "application/vnd.ms-excel", "application/x-msexcel"],
    ".xlsx": ["application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    ".xlt": ["application/excel", "application/x-excel", "application/vnd.ms-excel", "application/x-msexcel"],
    ".xm": ["audio/xm"],
    ".xml": ["text/xml", "application/xml"],
    ".xmz": ["xgl/movie"],
    ".xpix": ["application/x-vnd.ls-xpix"],
    ".xpm": ["image/xpm", "image/x-xpixmap"],
    ".x-png": ["image/png"],
    ".xsr": ["video/x-amt-showrun"],
    ".xul": ["application/vnd.mozilla.xul+xml"],
    ".xwd": ["image/x-xwd", "image/x-xwindowdump"],
    ".xyz": ["chemical/x-pdb"],
    ".z": ["application/x-compress", "application/x-compressed"],
    ".zip": ["application/zip", "multipart/x-zip", "application/x-zip-compressed", "application/x-compressed"],
    ".zoo": ["application/octet-stream"],
    ".zsh": ["text/x-script.zsh"],
}

# Zendesk

domain_zendesk = ''
url_zendesk = f'https://{domain_zendesk}.zendesk.com/api/v2/'
token_zendesk = ''
headers_default_zendesk = {"Authorization": "Basic " + token_zendesk}
user_zendesk = '/token'
password_zendesk = ''
credentials = user_zendesk, token_zendesk

# Freshdesk

domain_freshdesk = ""
parametros_freshdesk = {
    "campos_de_tickets": "ticket_fields",
    "campos_de_pessoas": "contact_fields",
    "campos_de_empresas": "company_fields",
    "agentes": "agentes",
    "empresas": "companies",
    "clientes": "contacts",
    "tickets": "tickets"
}
url_freshdesk = f"https://{domain_freshdesk}.freshdesk.com/api/v2/{parametros_freshdesk}"
token_freshdesk = ""

# Octadesk

sub_domain = ''
token_octadesk = ''
access_token_octadesk = ''
header_default_octadesk = {"Authorization": "Bearer " + access_token_octadesk}
url_octadesk = 'https://app.octadesk.com/login'
user_octadesk = ''
password_octadesk = ''
